from tkinter import *
root=Tk()
w=root.winfo_screenwidth()
h=root.winfo_screenheight()
root.geometry('%dx%d'%(w,h))
p=w//3
img=PhotoImage(file='.\\Bus_for_project.png')
frame1=Frame(root)
frame1.grid(row=0,column=0,columnspan=10)
Label(frame1,image=img).grid(row=0,column=6,padx=p)
Label(root,text='ONLINE BUS BOOKING SYSTEM',bg='light blue',fg='red',font='times 20 bold').grid(row=2,column=3,rowspan=3,padx=p)
Label(root,text=' ').grid(row=3,column=0)
Label(root,text=' ').grid(row=4,column=0)
Label(root,text='Name : RISHABH KUMAR ',fg='blue',font='times 18 bold').grid(row=5,column=3,rowspan=3,padx=p)  
Label(root,text=' ').grid(row=6,column=0)
Label(root,text=' ').grid(row=7,column=0)
Label(root,text='Er. : 211B253',fg='blue',font='times 18 bold').grid(row=8,column=3,rowspan=3,padx=p)
Label(root,text=' ').grid(row=9,column=0)
Label(root,text=' ').grid(row=10,column=0)
Label(root,text='Mobile : 9054489105',fg='blue',font='times 18 bold').grid(row=11,column=3,rowspan=3,padx=p)
Label(root,text=' ').grid(row=12,column=0)
Label(root,text=' ').grid(row=13,column=0)
Label(root,text='Submitted to : Dr. Mahesh Kumar',bg='light blue',fg='red',font='times 20 bold').grid(row=14,column=3,rowspan=3,padx=p)
Label(root,text=' ').grid(row=15,column=0)
Label(root,text=' ').grid(row=16,column=0)
Label(root,text='Project Based Learning',fg='red',font='times 18 bold').grid(row=22,column=3,rowspan=3,padx=p)
def cover_to_home(event):
   root.destroy()
   import SECOND_MAIN_MENU.py
root.bind("<KeyPress>",cover_to_home)
root.mainloop()
