from tkinter import *
from tkinter.messagebox import *
root=Tk()
root.title("Bus Booking System")
Label(root,text='').grid(row=0,column=0,padx=150)
w=root.winfo_screenwidth()
h=root.winfo_screenheight()
root.geometry('%dx%d'%(w,h))
p=w//3
img=PhotoImage(file='.\\Bus_for_project.png')
frame1=Frame(root)
frame1.grid(row=0,column=0,columnspan=10)
Label(frame1,image=img).grid(row=0,column=6,padx=p)
Label(root,text='Online Bus booking System',bg='light blue',fg='red',font='aerial 16 bold').grid(row=1,column=2)
Label(root,text=' ').grid(row=2,column=0,padx=150)
Label(root,text='Check Your Booking',fg='green',bg='light green',font='times 16 bold').grid(row=3,column=2)
Label(root,text=' ').grid(row=4,column=0,padx=150)
Label(root,text=' ').grid(row=5,column=0,padx=150)
Label(root,text='Enter Your Mobile No.',font='times 14 bold').grid(row=6,column=1)
mb=Entry(root,font='aerial 12 ')
mb.grid(row=6,column=2)
def popup():
   if mb.get()!='':
      showinfo('Booking Detail','Your Details')
      Label(root,text=' ').grid(row=8,column=0,padx=150)
      Label(root,text=' ').grid(row=9,column=0,padx=150)
      frame=Frame(root,relief='groove',bd=10)
      frame.grid(column=1,columnspan=8,padx=150)
      Label(frame,text='Passenger :' + name,font='aerial 14').grid(row=10,column=2)
      Label(frame,text=' ',font='aerial 14').grid(row=10,column=3)
      Label(frame,text='Gender :' + gen,font='aerial 14').grid(row=10,column=4)
      Label(frame,text='No. of seats :',font='aerial 14').grid(row=11,column=2)
      Label(frame,text=' ',font='aerial 14').grid(row=11,column=3)
      Label(frame,text='Phone :'+phone,font='aerial 14').grid(row=11,column=4)
      Label(frame,text='Age :'+ str(age),font='aerial 14').grid(row=12,column=2)
      Label(frame,text=' ',font='aerial 14').grid(row=12,column=3)
      Label(frame,text='Fare : '+ str(fare),font='aerial 14').grid(row=12,column=4)
      Label(frame,text='Booking Ref. :'+b_ref,font='aerial 14').grid(row=13,column=2)
      Label(frame,text=' ',font='aerial 14').grid(row=13,column=3)
      Label(frame,text='Travel on :' + travel_date,font='aerial 14').grid(row=13,column=4)
      Label(frame,text='Booked On:'+ book_date,font='aerial 14').grid(row=14,column=2)
      Label(frame,text=' ',font='aerial 14').grid(row=14,column=3)
      Label(frame,text='*Total fare is to be paid at the time of boarding' + str(fare*seat),font='times 12 italic').grid(row=15,column=2,columnspan=2)
   else:
      showerror('Error','Phone no. not inserted')
Button(root,text='Check Booking',command=popup).grid(row=6,column=3)
root.mainloop()
