from tkinter import *
from tkinter.messagebox import *
root=Tk()
Label(root,text='').grid(row=0,column=0,padx=150)
w=root.winfo_screenwidth()
h=root.winfo_screenheight()
root.geometry('%dx%d'%(w,h))
p=w//3
img=PhotoImage(file='.\\Bus_for_project.png')
frame1=Frame(root)
frame1.grid(row=0,column=0,columnspan=10)
Label(frame1,image=img).grid(row=0,column=6,padx=p)
Label(frame1,text='Online Bus booking System',bg='light blue',fg='red',font='aerial 16 bold').grid(row=1,column=6,padx=p)
Label(root,text=' ').grid(row=8,column=0,padx=150)
Label(root,text=' ').grid(row=9,column=0,padx=150)
frame=Frame(root,relief='groove',bd=10)
frame.grid(column=1,columnspan=8,padx=150)
Label(frame,text='Passenger :         ',font='aerial 14').grid(row=10,column=2)
Label(frame,text=' ',font='aerial 14').grid(row=10,column=3)
Label(frame,text='Gender :     ',font='aerial 14').grid(row=10,column=4)
Label(frame,text='No. of seats :      ',font='aerial 14').grid(row=11,column=2)
Label(frame,text=' ',font='aerial 14').grid(row=11,column=3)
Label(frame,text='Phone :          ',font='aerial 14').grid(row=11,column=4)
Label(frame,text='Age :       ',font='aerial 14').grid(row=12,column=2)
Label(frame,text=' ',font='aerial 14').grid(row=12,column=3)
Label(frame,text='Fare :          ',font='aerial 14').grid(row=12,column=4)
Label(frame,text='Booking Ref. :      ',font='aerial 14').grid(row=13,column=2)
Label(frame,text=' ',font='aerial 14').grid(row=13,column=3)
Label(frame,text='Travel on :         ',font='aerial 14').grid(row=13,column=4)
Label(frame,text='Boardin Point :       ',font='aerial 14').grid(row=14,column=2)
Label(frame,text=' ',font='aerial 14').grid(row=14,column=3)
Label(frame,text='Destination :        ',font='aerial 14').grid(row=14,column=4)
Label(frame,text='*Total fare is to be paid at the time of boarding',font='times 12 italic').grid(row=15,column=2,columnspan=2)
root.mainloop()
